#!/bin/sh

# Pre-commit hook to format changed files

stagedFiles=$(git diff --staged --name-only)

./gradlew spotlessApply

for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done
